Error in run: {'Pretraining_weights': '/home/tobias.rothlin/data/TrainingSnapshots/Pretraining_1_1/model_end_of_epoch_0.pt', 'Pretraining_config': '/home/tobias.rothlin/data/TrainingSnapshots/Pretraining_1_1/run_config.json', 'DatasetConfig': {'base_model': 'openai/clip-vit-large-patch14-336', 'augmentaion_pipeline': [{'name': 'RandomRotation', 'params': {'degrees': 10}}, {'name': 'ColorJitter', 'params': {'brightness': 0.5, 'contrast': 0.2, 'saturation': 0.4, 'hue': 0.01}}, {'name': 'RandomPerspective', 'params': {'distortion_scale': 0.2, 'p': 0.5}}], 'normalize_labels': True, 'use_cached_dataloader': False, 'load_for_contrast_learning': False, 'use_pre_calculated_embeddings': False, 'load_pooling_output': False, 'use_gaussian_smoothing': True, 'workers': 4}, 'DataLoaderConfig': {'Train': {'batch_size': 64, 'shuffle': True, 'num_workers': 8, 'pin_memory': True, 'prefetch_factor': 20}, 'Test': {'batch_size': 64, 'shuffle': True, 'num_workers': 8, 'pin_memory': True, 'prefetch_factor': 20}}, 'ModelConfig': {'use_location_head': False, 'use_similarity_head': False, 'freeze_base_model': True, 'RegressionHead': {'layer_group': [[{'type': 'Linear', 'in_features': 1024, 'out_features': 1024}, {'type': 'Dropout', 'p': 0.3}, {'type': 'LayerNorm', 'normalized_shape': 1024}, {'type': 'ReLU'}], [{'type': 'Linear', 'in_features': 1024, 'out_features': 512}, {'type': 'Dropout', 'p': 0.2}, {'type': 'LayerNorm', 'normalized_shape': 512}, {'type': 'ReLU'}], [{'type': 'Linear', 'in_features': 512, 'out_features': 256}, {'type': 'Dropout', 'p': 0.1}, {'type': 'LayerNorm', 'normalized_shape': 256}, {'type': 'ReLU'}], [{'type': 'Linear', 'in_features': 256, 'out_features': 64}, {'type': 'Dropout', 'p': 0.1}, {'type': 'LayerNorm', 'normalized_shape': 64}, {'type': 'ReLU'}], [{'type': 'Linear', 'in_features': 64, 'out_features': 32}, {'type': 'Dropout', 'p': 0.1}, {'type': 'LayerNorm', 'normalized_shape': 32}, {'type': 'ReLU'}], [{'type': 'Linear', 'in_features': 32, 'out_features': 2}, {'type': 'Tanh'}]]}}, 'TrainingConfig': {'Epochs': 10, 'SaveEvery': 10000, 'RunName': 'Regression_Pretrained_0', 'SnapshotPath': '/home/tobias.rothlin/data/TrainingSnapshots', 'LogMLFlow': False, 'MLFlowExperimentName': 'ClipLocationDecoder', 'GradientAccumulationSteps': 1, 'ContrastLearningStrategy': None, 'LearningRate': 0.0001, 'Amsgrad': True, 'WeightDecay': 0.0001, 'Betas': [0.9, 0.98], 'Gamma': 0.9}}
Caught FileNotFoundError in DataLoader worker process 6.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/tobias.rothlin/GeoLocalization/src/DGX1/src/RegressionPretraining/GeoLocalizationDataset.py", line 160, in __getitem__
    image = self.__load_image(image_path)
  File "/home/tobias.rothlin/GeoLocalization/src/DGX1/src/RegressionPretraining/GeoLocalizationDataset.py", line 177, in __load_image
    image = Image.open(image_path)
  File "/usr/local/lib/python3.10/dist-packages/PIL/Image.py", line 3092, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/tobias.rothlin/data/GeoDataset/Train/Batch_841/ehktl-D-zot-9cgBTC8B8-.jpg'
Traceback (most recent call last):
  File "/home/tobias.rothlin/GeoLocalization/src/DGX1/src/RegressionPretraining/main.py", line 127, in <module>
    trainer.train()
  File "/home/tobias.rothlin/GeoLocalization/src/DGX1/src/RegressionPretraining/SingleGPUTrainer.py", line 249, in train
    self.__run_epoch(self.train_dataloader, epoch,with_logging=True,is_train=True)
  File "/home/tobias.rothlin/GeoLocalization/src/DGX1/src/RegressionPretraining/SingleGPUTrainer.py", line 196, in __run_epoch
    for batch_idx, batch in enumerate(progress_bar):
  File "/usr/local/lib/python3.10/dist-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.10/dist-packages/torch/_utils.py", line 693, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 6.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/tobias.rothlin/GeoLocalization/src/DGX1/src/RegressionPretraining/GeoLocalizationDataset.py", line 160, in __getitem__
    image = self.__load_image(image_path)
  File "/home/tobias.rothlin/GeoLocalization/src/DGX1/src/RegressionPretraining/GeoLocalizationDataset.py", line 177, in __load_image
    image = Image.open(image_path)
  File "/usr/local/lib/python3.10/dist-packages/PIL/Image.py", line 3092, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/tobias.rothlin/data/GeoDataset/Train/Batch_841/ehktl-D-zot-9cgBTC8B8-.jpg'


